#!/usr/bin/env bash

. ./node_modules/release-util-fnd/lib.sh

pre_release_checks
npm test

target_dir=`create_package`
# include stand-alone (minified) version
npm run standalone
target="$target_dir/loader.min.js"
intro="// tiny-loader v$version <https://github.com/FND/tiny-script-loader> (Apache License 2.0)"
echo "$intro" > "$target"
cat loader.min.js >> "$target"

publish_package
